<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod1.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod2.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod1.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod2.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod1.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod2.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod1.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod2.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod1.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod2.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod1.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="thumbnail">
        <a href="#">
            <img src="<?php echo PUBLIC_URL; ?>/images/prod1.gif" alt="" style="width:100%">
        </a>
        <div class="caption">
            <h4>
                <a href="#">What is Lorem Ipsum?</a>
            </h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled</p>

            <p>Price:
                <strong>$ 500</strong>
            </p>

        </div>


    </div>
</div>